image: node:14.9.0-alpine

stages:
    - deploy

deploy_development:
    stage: deploy
    image: ruby
    script:
        - apt update -qy
        - apt install -y ruby-dev
        - gem install dpl
        - gem install faraday -v 1.8.0
        - dpl --provider=heroku --app=comiconics-dev --api-key=$HEROKU_API_KEY
    only:
        - dev
